version: 0.2


env:
  shell: bash

phases:
  pre_build:
    commands:
      - "docker login -u lumel -p $PASSWORD"
      - export CURRENT_BRANCH=$(git symbolic-ref HEAD --short 2>/dev/null)
      - if grep -q '/' <<< $CURRENT_BRANCH ; then export CURRENT_BRANCH=$(cut -f2 -d/  ) <<< $CURRENT_BRANCH; fi
      - echo Branch is $CURRENT_BRANCH

  build:
    commands:
      - docker build -t lumel/unifi-controller:$CURRENT_BRANCH .

  post_build:
    commands:
      - docker push lumel/unifi-controller:$CURRENT_BRANCH

