version: 0.2


env:
  shell: bash

phases:
  pre_build:
    commands:
      - "docker login -u lumel -p $PASSWORD"
      - echo Branch is $BRANCH
      - "echo Branch is $BRANCH"
      - ls -la
      - BRANCH=$(git status | grep 'On branch' | cut -f3 -d\  )
      - if grep -q '/' <<< $BRANCH; then export BRANCH=$( cut -f2 -d/  <<< $BRANCH); fi

  build:
    commands:
      - docker build -t lumel/unifi-controller:$BRANCH .

  post_build:
    commands:
      - docker push lumel/unifi-controller:$BRANCH


