version: 0.2


env:
  shell: bash

phases:
  pre_build:
    commands:
      - "docker login -u lumel -p $PASSWORD"
      - echo Branch is $BRANCH
      - "echo Branch is $BRANCH"

  build:
    commands:
      - docker build -t lumel/unifi-controller:$BRANCH .

  post_build:
    commands:
      - docker push lumel/unifi-controller:$BRANCH

