version: 0.2


env:
  shell: bash

phases:
  pre-build:
    commands:
      - 'docker login -u lumel -p $PASSWORD'

  build:
    commands:
      - docker build -t lumel/unifi-controller:codepipeline .

  post-build:
    commands:
	  - docker push lumel/unifi-controller:codepipeline

