version: 0.2


env:
  shell: bash

phases:
  pre_build:
    commands:
      - "docker login -u lumel -p $PASSWORD"
      - echo Branch is $BRANCH
      - "echo Branch is $BRANCH"
      - ls -la
      - ls -l .git/
      - cat .git/HEAD
      - BRANCH=$(cut -f2 -d\  < .git/HEAD); echo B=$BRANCH
      - echo B=$BRANCH
      - BRANCH=${BRANCH#refs/heads/}; echo B=$BRANCH
      - if grep -q '/' <<< $BRANCH; then export BRANCH=$( cut -f2 -d/  <<< $BRANCH); fi
      - echo $BRANCH
      - git status
      - export
      - false

  build:
    commands:
      - docker build -t lumel/unifi-controller:$BRANCH .

  post_build:
    commands:
      - docker push lumel/unifi-controller:$BRANCH


