version: 0.2


env:
  shell: bash
  parameter-store:
    DOCKER_USERNAME: uk.co.lumel.credentials.docker_username
    DOCKER_PASSWORD: uk.co.lumel.credentials.docker_password 

phases:
  pre_build:
    commands:
      - "docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD"
      - echo Branch is $BRANCH

  build:
    commands:
      - docker build -t lumel/unifi-controller:$BRANCH .

  post_build:
    commands:
      - docker push lumel/unifi-controller:$BRANCH


